# Generated by Django 2.2.3 on 2020-07-02 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(default='', max_length=8, primary_key=True, serialize=False)),
                ('profile', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=16, unique=True)),
                ('student_id', models.CharField(max_length=10, unique=True)),
                ('qq', models.CharField(max_length=10)),
                ('class_belong', models.CharField(default='', max_length=32)),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1)),
                ('profile', models.TextField(default='1')),
                ('first_will', models.IntegerField(choices=[(1, '研发部'), (2, 'acm 部'), (3, 'ctf 部')], default=1)),
                ('second_will', models.IntegerField(choices=[(1, '研发部'), (2, 'acm 部'), (3, 'ctf 部')], default=1)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Department')),
            ],
        ),
    ]
