# Generated by Django 2.2.5 on 2020-07-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=16)),
                ('student_id', models.CharField(max_length=10)),
                ('avatar', models.CharField(blank=True, max_length=128, null=True)),
                ('qq', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=4)),
                ('first_will', models.CharField(blank=True, choices=[('研发部', 1), ('acm 部', 2), ('行政部', 3), ('ctf 部', 4)], max_length=12, null=True)),
                ('second_will', models.CharField(blank=True, choices=[('研发部', 1), ('acm 部', 2), ('行政部', 3), ('ctf 部', 4)], max_length=12, null=True)),
            ],
        ),
    ]
