# Generated by Django 2.2.5 on 2020-07-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[('student', 1), ('charger', 2), ('admin', 3)], default=1),
        ),
    ]
