# Generated by Django 2.2.5 on 2020-07-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_will',
            field=models.IntegerField(blank=True, choices=[('研发部', 1), ('acm 部', 2), ('行政部', 3), ('ctf 部', 4)], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_will',
            field=models.IntegerField(blank=True, choices=[('研发部', 1), ('acm 部', 2), ('行政部', 3), ('ctf 部', 4)], null=True),
        ),
    ]
