# Generated by Django 2.2.5 on 2020-07-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200701_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_will',
            field=models.IntegerField(blank=True, choices=[(1, '研发部'), (2, 'acm 部'), (3, '行政部'), (4, 'ctf 部')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_will',
            field=models.IntegerField(blank=True, choices=[(1, '研发部'), (2, 'acm 部'), (3, '行政部'), (4, 'ctf 部')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'student'), (2, 'charger'), (3, 'admin')], default=1),
        ),
    ]
